### PR TITLE
Refactor `created` function from room.html

### LINKED ISSUE #25: Split up the huge created() function
Currently, the `created()` function in `room.html` is quite monolithic. It would be nice to split this into several smaller methods to make the code more readable.

### PR DESCRIPTION
**Pull request by gahag**
* **Please check if the PR fulfills these requirements**
- [x] You've followed the [contributing guidelines](CONTRIBUTING.md)
- [x] You've adhered to the [code of conduct](CODE_OF_CONDUCT.md)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- [ ] Bug Fix
- [ ] New Feature
- [ ] Documentation Update
- [x] Other: refactor

## If bug fixes or new features

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

Fixes #25

### CODE REVIEW

**Comment by gahag** [comment]
@phazonoverload please tell me if any further improvements can be made. Thank you.

**Comment by phazonoverload** [comment]
Awesome, thank you. I think the event handlers should be in their own method too - so one for streamCreated, one for streamDestroyed and one for the signal

**Comment by gahag** [comment]
Sure, I'll update it right away.

**Comment by gahag** [comment]
@phazonoverload Thank you for the suggestion. It is implemented now.

**Comment by phazonoverload** [comment]
Solid changed, thank you.

**Pull request merged**
