### PR TITLE
Basic styling for the index and room pages

### PR DESCRIPTION
**Pull request by C-Zekeri**
Added basic styling to the client pages. This is an enhancement, fixing #7 . I made the styling very minimalistic, as there is little content available. As new content is added, I'll be glad to contribute more styling. If there is anything you'd like me to fix or improve, please let me know.
Thank you!

### CODE REVIEW

**Comment by phazonoverload** [comment]
Thank you so much for this! I'll review it in this Friday's show

**Comment by C-Zekeri** [comment]
> Deploy request for _build-a-thing-video_ accepted.
> 
> Accepted with commit [67e5e2c](https://github.com/nexmo-community/build-a-thing-video/commit/67e5e2cf747c2d183eef20e5d77d41cc45dadcc1)
> 
> https://app.netlify.com/sites/build-a-thing-video/deploys/5f7c9be6a624fc0007d8433a

You're welcome, and thank you too.

**Comment by phazonoverload** [comment]
Thanks - looks good! I really appreciate the contribution and I'll merge this in. 

I'm curious why you chose to make the publisher area so much bigger than the subscribers - in most other video conferencing applications, the subscribers (ie. everyone except you) is bigger. I'd encourage you to submit a further PR at some point in the near future to change this.

**Comment by phazonoverload** [comment]
I've opened a new pull request for the additional change #14

**Comment by C-Zekeri** [comment]
Oh, I understand now. That was a mistake, and I'll work on fixing it as soon as I can. Thank you!

**Pull request merged**
